# The URL the site will be built for
base_url = "http://philipdaniels.com/rsforcs"
title = "Rust for C# Programmers"
description = "Everything necessary for C# programmers to learn Rust."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

theme = "rsforcs-theme"

[extra]
# Put all your custom variables here
author = "Philip Daniels"
